 steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  
 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
  
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'zeta-time-338114/cloud-spanner-build', '--build-arg=JAR_FILE=target/build-artifact', '.']
  images: ['gcr.io/zeta-time-338114/cloud-spanner-build']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
           'gcr.io/zeta-time-338114/cloud-spanner-build']
options:
  logging: CLOUD_LOGGING_ONLY
